### ISSUE TITLE
[Urgent]Can't bypass the CF anti-bot protection & get the chapter lists on MD

### ISSUE THREAD

**Issue by JokoeSukri** [riderkick/FMD#1699]
And then, can we bypass the chaptcha ??

**Comment by Nandaka** [comment]
Try to login to mangadex from browser and copy the cookie values and paste it in the advanced option.

![image](https://user-images.githubusercontent.com/836867/54091189-047f3600-43b8-11e9-9967-93eae31ca186.png)

**Comment by JokoeSukri** [comment]
@Nandaka 
I got the cookies, so how do I input it??
![Screenshot_12](https://user-images.githubusercontent.com/32964994/54091492-fe8f5200-43c3-11e9-95c6-b977bdf8fe8b.jpg)

**Comment by JokoeSukri** [comment]
Nevermind, I got it now

**Comment by Tmp341** [comment]
Don't forget. If you have fast download speeds, under advanced settings, use low task limits etc.

**Comment by Thrieze** [comment]
Huh odd, I put in the content of the _cfduid but it doesn't work, how much exactly should go in the cookies area.
Edit: For clarification, I mean, do i put _cfduid then a space then the content, or just the content of it? Or the other cookies as well. I feel like ive tried combos of everything and I must be missing something.

**Comment by arbiter9605** [comment]
A little more clarification is needed for rest of us never had to mess with this stuff before.

**Comment by TopCat00** [comment]
I put in all the cookies but also had to set the User Agent string to be the same as the browser used to access the site before it would work.

**Comment by arbiter9605** [comment]
i put data in there i pulled from firefox web console using "document.cookie" but not working for me so i must have syntax wrong on something but never had to deal with doing this before hence would like a line showing what to put in which can edit out cookie hash with **** so i can fill in blanks with my data.

According though to MD's site its a ddos attack that triggered the captacha so just waiting in time it should resolve itself.

**Comment by Thrieze** [comment]
Oh huh, It just worked. I put this into cookies. ignore the asterisks, just a placeholder, its the content of the _cfduid cookie.

__cfduid d8cb64147475e7a978f441ff1*****************

**Comment by Caeswen** [comment]
Hi there. I don't know if I am doing something wrong and would like some assistance. But I've followed what I think to be the correct way to do this and nothing is showing up. Is what I have done the correct way to do this?
See below image. 
![help](https://user-images.githubusercontent.com/36606626/54496686-a36fca80-48af-11e9-8a51-b571e4aa54ed.jpg)

**Comment by Geese1** [comment]
I'd like to get some help as well. Mine was working fine up until yesterday without having to do any changes to the advanced settings, but today nothing will work for MangaDex. Checked and saw that they're now requesting a CAPTCHA, so I came here to see if there were any solutions. 

I've tried doing everything suggested in this thread, and still no luck. My settings look like the image posted by Caeswen, so I don't know what else to try at this point.

**Comment by arbiter9605** [comment]
MD is under another attack, when attack passes and CF stops freaking out it will start to work again.

edit: its working again now that ddos captcha has calmed down.

**Comment by japzone1** [comment]
1. Go to MangaDex, pass the captcha, and log into your user account
2. Open your browser's developer tools, go to the Networking tab, refresh the age, then select a random item that appears in the list
3. Under "Headers", copy the text that comes after "User-Agent:", go to FMD --> Options --> Sites --> Advanced --> MangaDex, then paste the text next to "UserAgent"
4. Go back to the browser and go to the "Cookies" tab next to "Headers" from before, now copy each cookie into FMD, next to "Cookies", in this format: 
```
_cfduid=XXXXXXXXXXXXXXXXXXXXX; cf_clearance=XXXXXXXXXXXXXXXXXXX; mangadex=XXXXXXXXXXXXXXXXXXXXXXXXXX; mangadex_rememberme_token=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX; mangadex_session=XXXXXXXXXXXXXXXXXXXXXXXXX
```
5. Now in FMD set "Enabled" to True, and set all the "Max-" and "UpdateList-" options to `1`.

Now refresh your Favorites to see if it works.

PS: These instructions were made using Firefox. Location of some info might be different in your browser.

**Comment by Geese1** [comment]
> 1. Go to MangaDex, pass the captcha, and log into your user account
> 2. Open your browser's developer tools, go to the Networking tab, refresh the age, then select a random item that appears in the list
> 3. Under "Headers", copy the text that comes after "User-Agent:", go to FMD --> Options --> Sites --> Advanced --> MangaDex, then paste the text next to "UserAgent"
> 4. Go back to the browser and go to the "Cookies" tab next to "Headers" from before, now copy each cookie into FMD, next to "Cookies", in this format:
> 
> ```
> _cfduid=XXXXXXXXXXXXXXXXXXXXX; cf_clearance=XXXXXXXXXXXXXXXXXXX; mangadex=XXXXXXXXXXXXXXXXXXXXXXXXXX; mangadex_rememberme_token=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX; mangadex_session=XXXXXXXXXXXXXXXXXXXXXXXXX
> ```
> 1. Now in FMD set "Enabled" to True, and set all the "Max-" and "UpdateList-" options to `1`.
> 
> Now refresh your Favorites to see if it works.
> 
> PS: These instructions were made using Firefox. Location of some info might be different in your browser.

Thanks for the detailed instructions!

I'm using Chrome, but the directions were the same there as Firefox, so no issues. My problem was I was only using the "__cfduid cookie", and not all the rest of them. I also hadn't changed the "Max" and "UpdateList" options from their default zero, although I'm not sure if that made any difference or not. Anyway, just made the additional changes per your post and now everything works great!

Thanks for all your help!

**Comment by japzone1** [comment]
> Thanks for the detailed instructions!
> 
> I'm using Chrome, but the directions were the same there as Firefox, so no issues. My problem was I was only using the "__cfduid cookie", and not all the rest of them. I also hadn't changed the "Max" and "UpdateList" options from their default zero, although I'm not sure if that made any difference or not. Anyway, just made the additional changes per your post and now everything works great!
> 
> Thanks for all your help!

Glad it worked.

Setting everything to `1` forces FMD to only make one connection at a time with MangaDex, heavily reducing the possibility of CF flagging it as a bot/DDOS. This slows downloads and how fast your Favorites are checked, but it's better than being IP banned.

PS: You might have to update the `cf` cookies every day or so, since they expire. You'll know you need to update them when downloads stop working, or Favorites start showing `0` chapters.

**Comment by Geese1** [comment]
> > Thanks for the detailed instructions!
> > I'm using Chrome, but the directions were the same there as Firefox, so no issues. My problem was I was only using the "__cfduid cookie", and not all the rest of them. I also hadn't changed the "Max" and "UpdateList" options from their default zero, although I'm not sure if that made any difference or not. Anyway, just made the additional changes per your post and now everything works great!
> > Thanks for all your help!
> 
> Glad it worked.
> 
> Setting everything to `1` forces FMD to only make one connection at a time with MangaDex, heavily reducing the possibility of CF flagging it as a bot/DDOS. This slows downloads and how fast your Favorites are checked, but it's better than being IP banned.
> 
> PS: You might have to update the `cf` cookies every day or so, since they expire. You'll know you need to update them when downloads stop working, or Favorites start showing `0` chapters.

That makes sense. Was wondering why my downloads seemed a bit slower than normal (I'm on a gigabit connection), and thought it was just the MangaDex server being overwhelmed.

As you said though, it's a better option than having to use a VPN (which I've done in the past), which would slow things down even more.

Oh, and thanks for the tip about refreshing the cf cookies if needed. I'll be on the lookout for that.

**Comment by arbiter9605** [comment]
Sadly for me doesn't work when ddos captcha is up. I don't see the "mangadex=" one in firefox but does give me it in IE10. Tried doing it using ff, IE10 and chrome so pretty much just stuck waiting til CF ddos protection takes a chill pill.

**Comment by japzone1** [comment]
> 
> 
> Sadly for me doesn't work when ddos captcha is up. I don't see the "mangadex=" one in firefox but does give me it in IE10. Tried doing it using ff, IE10 and chrome so pretty much just stuck waiting til CF ddos protection takes a chill pill.

Did you follow all my directions exactly? At the very least you should have both of the `cf` cookies and the Browser's UserAgent copied into FMD. The `mangadex` cookies don't appear unless you log into an account on MangaDex.

**Comment by arbiter9605** [comment]
"_cfduid=XXXXXXXXXXXXXXXXXXXXX; cf_clearance=XXXXXXXXXXXXXXXXXXX; mangadex=XXXXXXXXXXXXXXXXXXXXXXXXXX; mangadex_rememberme_token=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX; mangadex_session=XXXXXXXXXXXXXXXXXXXXXXXXX"

Yes i did and Yes i was logged in.  the mangadex one i don't see is first one, the _rememberme_ and _session one's show up.

**Comment by Geese1** [comment]
> "_cfduid=XXXXXXXXXXXXXXXXXXXXX; cf_clearance=XXXXXXXXXXXXXXXXXXX; mangadex=XXXXXXXXXXXXXXXXXXXXXXXXXX; mangadex_rememberme_token=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX; mangadex_session=XXXXXXXXXXXXXXXXXXXXXXXXX"
> 
> Yes i did and Yes i was logged in. the mangadex one i don't see is first one, the _rememberme_ and _session one's show up.

Just a head's up, but the "__cfduid" has two underscores in front of it. You typed just one above, so I wasn't sure if you were aware of that. Could possibly make the difference.

**Comment by echoPN** [comment]
Thanks, guys...
This trick works on Kissmanga too...

**Comment by Tmp341** [comment]
@japzone1 Thank you. I've added your workaround to [FAQ](https://github.com/riderkick/FMD/wiki/FAQ/fceef23ebb4b775fab6909eab72915541024eded#cannot-download-from-mangadexkissmanga)

**Comment by admiralmikan** [comment]
I almost freak out when suddenly I couldn't download from MD anymore. Tried above info, still didn't work. Turned out I need to add Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36 on User Agent lol
